[package]
name = "oracle"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
o1-utils = { path = "../utils" }
once_cell = "1"
rand = "0.8.0"
rayon = "1"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"

mina-curves = { path = "../curves" }

# for ocaml
ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { path = "../ocaml/ocaml-gen", optional = true }

[dev-dependencies]
serde_json = "1.0"
hex = "0.4"
ark-serialize = "0.3.0"

[features]
default = []
ocaml_types = [ "ocaml", "ocaml-gen", ]
